steps:
  - id: install-dependencies
    name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
  - id: build-package
    name: python
    entrypoint: python
    args: ["-m", "build"]
  - id: validate-package
    name: python
    entrypoint: python
    args: ["-m", "twine", "check", "dist/*"]
  - id: distribute-package
    name: python
    entrypoint: bash
    args: ["-c", "python -m twine upload /workspace/dist/* --repository pypi -u $$PYPI_USER -p $$PYPI_TOKEN"] # , twine upload --repository pypi
    secretEnv: ['PYPI_USER', 'PYPI_TOKEN']
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET}/${TAG_NAME}/'
    paths: ['./dist/*']
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/pypi-user/versions/3
    env: PYPI_USER
  - versionName: projects/${PROJECT_ID}/secrets/pypi-token/versions/1
    env: PYPI_TOKEN